theme: jekyll-theme-merlot
title: 明哥讲道
description: 天道有缺，人道补之。
permalink: /:year/:month/:day/:title
excerpt_separator: <!--以上为摘要内容-->
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins: [jekyll-paginate]
paginate: 6